package dev.mc2p.deploy;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.LinkedHashMap;
import java.util.Map;

import dev.mc2p.common.util.Tokens;

/**
 * Deployment helper CLI ({@code ./gradlew deploy:run --args="..."}).
 *
 * <p>
 * Generates per-role tokens and a shared proxy secret, writes the matching config files
 * and an agent-side {@code mcpServers} JSON snippet for the chosen topology
 * ({@code standalone} single server, or {@code multi} via the Velocity proxy). Secrets
 * are printed exactly once; config files reference them via env vars.
 *
 * <pre>
 *   deploy gen-config --topology standalone [--out &lt;dir&gt;] [--host &lt;host&gt;] [--port &lt;port&gt;]
 *   deploy gen-config --topology multi       [--out &lt;dir&gt;] [--host &lt;host&gt;] [--port &lt;port&gt;]
 * </pre>
 */
public final class DeployCli {

    private static final String HELP = """
            MC2P deploy helper

            Usage:
              deploy gen-config --topology <standalone|multi> [--out <dir>] [--host <host>] [--port <port>]

            Generates tokens + a proxy secret, writes config.yml and mcpServers.json for the
            chosen topology, and prints the env-var exports you must set on the hosts.
            """;

    public static void main(String[] args) throws Exception {
        String topology = "standalone";
        String out = "deploy-out";
        String host = "localhost";
        int port = 8443;

        for (int i = 0; i < args.length; i++) {
            switch (args[i]) {
                case "gen-config" -> {
                }
                case "--topology" -> topology = value(args, ++i);
                case "--out" -> out = value(args, ++i);
                case "--host" -> host = value(args, ++i);
                case "--port" -> port = Integer.parseInt(value(args, ++i));
                case "--help", "-h" -> {
                    System.out.println(HELP);
                    return;
                }
                default -> {
                    System.err.println("Unknown argument: " + args[i]);
                    System.err.println(HELP);
                    System.exit(2);
                }
            }
        }

        switch (topology) {
            case "standalone" -> genStandalone(Path.of(out), host, port);
            case "multi" -> genMulti(Path.of(out), host, port);
            default -> {
                System.err.println("Unknown topology: " + topology);
                System.exit(2);
            }
        }
    }

    private static String value(String[] args, int index) {
        if (index >= args.length) {
            System.err.println("Missing value for argument.");
            System.exit(2);
            return "";
        }
        return args[index];
    }

    private static void genStandalone(Path outDir, String host, int port) throws IOException {
        Files.createDirectories(outDir);
        String reader = Tokens.generateToken();
        String ops = Tokens.generateToken();
        String admin = Tokens.generateToken();

        String config = """
                # MC2P backend plugin configuration (generated by deploy).
                mode: standalone
                serverId: main-01
                mcp:
                  bind: 0.0.0.0
                  port: %d
                  endpoint: /mcp
                  body-limit-bytes: 65536
                  tls:
                    mode: selfsigned
                    keystore: keystore.p12
                    password-env: MC2P_KEYSTORE_PW
                auth:
                  tokens:
                    reader: env:MC2P_TOKEN_READER
                    ops: env:MC2P_TOKEN_OPS
                    admin: env:MC2P_TOKEN_ADMIN
                  ip-allowlist: []
                  rate-limit:
                    tokens-per-second: 5
                    burst: 20
                """.formatted(port);

        write(outDir.resolve("config.yml"), config);

        Map<String, Object> mcpServers = new LinkedHashMap<>();
        mcpServers.put("mcpServers", Map.of("mc2p", Map.of(
                "url", "https://" + host + ":" + port + "/mcp",
                "headers", Map.of("Authorization", "Bearer <TOKEN>"),
                "type", "streamable-http",
                "mcpServers-type", "streamable-http")));

        write(outDir.resolve("mcpServers.json"), toJson(mcpServers));

        System.out.println("Standalone (single server) deployment generated in " + outDir.toAbsolutePath());
        System.out.println();
        System.out.println("Set these env vars on the Paper host (add to your startup script):");
        printEnv("MC2P_TOKEN_READER", reader);
        printEnv("MC2P_TOKEN_OPS", ops);
        printEnv("MC2P_TOKEN_ADMIN", admin);
        System.out.println();
        System.out.println("Open ONE port: " + port + " on the Paper box.");
        System.out.println("Agent endpoint: https://" + host + ":" + port + "/mcp");
        System.out.println("Trust: with tls.mode=selfsigned, export the generated cert"
                + " (plugins/MC2P/keystore.p12) and pin it client-side; never insecureSkipVerify.");
        System.out.println();
        System.out.println("mcpServers.json snippet: use the token for the role you give the agent.");
    }

    private static void genMulti(Path outDir, String host, int port) throws IOException {
        Files.createDirectories(outDir);
        String reader = Tokens.generateToken();
        String ops = Tokens.generateToken();
        String admin = Tokens.generateToken();
        String proxySecret = Tokens.generateToken();

        String config = """
                # MC2P proxy plugin configuration (generated by deploy).
                serverId: proxy-01
                mcp:
                  bind: 0.0.0.0
                  port: %d
                  endpoint: /mcp
                  tls:
                    mode: selfsigned
                    keystore: keystore.p12
                    password-env: MC2P_KEYSTORE_PW
                  body-limit-bytes: 65536
                auth:
                  tokens:
                    reader: env:MC2P_TOKEN_READER
                    ops: env:MC2P_TOKEN_OPS
                    admin: env:MC2P_TOKEN_ADMIN
                  ip-allowlist: []
                  rate-limit:
                    tokens-per-second: 5
                    burst: 20
                servers: {}
                rpc:
                  secret-env: MC2P_PROXY_SECRET
                  channel: mc2p:rpc
                  timeout-ms: 5000
                  max-chunks: 8
                audit:
                  file: logs/mcp-proxy-audit.log
                  max-mb: 50
                  max-files: 5
                """.formatted(port);

        write(outDir.resolve("proxy-config.yml"), config);

        Map<String, Object> mcpServers = new LinkedHashMap<>();
        mcpServers.put("mcpServers", Map.of("mc2p", Map.of(
                "url", "https://" + host + ":" + port + "/mcp",
                "headers", Map.of("Authorization", "Bearer <TOKEN>"),
                "type", "streamable-http",
                "mcpServers-type", "streamable-http")));

        write(outDir.resolve("mcpServers.json"), toJson(mcpServers));

        System.out.println("Multi-server (Velocity proxy) deployment generated in " + outDir.toAbsolutePath());
        System.out.println();
        System.out.println("PROXY host - set these env vars:");
        printEnv("MC2P_TOKEN_READER", reader);
        printEnv("MC2P_TOKEN_OPS", ops);
        printEnv("MC2P_TOKEN_ADMIN", admin);
        printEnv("MC2P_PROXY_SECRET", proxySecret);
        System.out.println();
        System.out.println("Each BACKEND Paper host - set ONLY the proxy secret (backend opens no port):");
        printEnv("MC2P_PROXY_SECRET", proxySecret);
        System.out.println();
        System.out.println("Backend config.yml: mode: auto (resolves to backend when the secret is set).");
        System.out.println("Open ONE port: " + port + " on the proxy box.");
        System.out.println("Agent endpoint: https://" + host + ":" + port + "/mcp");
        System.out.println("Tool calls target backends via the `server` parameter (serverId).");
        System.out.println("Trust: with tls.mode=selfsigned, export the proxy's generated cert and pin it"
                + " client-side; never insecureSkipVerify.");
        System.out.println();
        System.out.println("mcpServers.json snippet: use the token for the role you give the agent.");
    }

    private static void printEnv(String name, String value) {
        System.out.println("  export " + name + "=\"" + value + "\"");
    }

    private static void write(Path file, String content) throws IOException {
        Files.writeString(file, content, StandardCharsets.UTF_8);
        try {
            Files.setPosixFilePermissions(file, PosixFilePermissions.fromString("rw-------"));
        } catch (UnsupportedOperationException ignored) {
            // non-POSIX filesystem
        }
        System.out.println("  wrote " + file.toAbsolutePath());
    }

    private static String toJson(Object value) {
        StringBuilder sb = new StringBuilder();
        appendJson(sb, value);
        return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private static void appendJson(StringBuilder sb, Object value) {
        if (value == null) {
            sb.append("null");
        } else if (value instanceof String s) {
            sb.append('"').append(escape(s)).append('"');
        } else if (value instanceof Number || value instanceof Boolean) {
            sb.append(value);
        } else if (value instanceof Map<?, ?> map) {
            sb.append('{');
            boolean first = true;
            for (Map.Entry<?, ?> e : map.entrySet()) {
                if (!first) {
                    sb.append(',');
                }
                first = false;
                sb.append('"').append(escape(String.valueOf(e.getKey()))).append("\":");
                appendJson(sb, e.getValue());
            }
            sb.append('}');
        } else {
            sb.append('"').append(escape(String.valueOf(value))).append('"');
        }
    }

    private static String escape(String s) {
        StringBuilder out = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> out.append(c);
            }
        }
        return out.toString();
    }

    private DeployCli() {
    }
}